import { Command } from "commander";
import { prisma } from "@civic/db";
import { MODEL_A, MODEL_B } from "./llm.js";
import { runExtraction } from "./pipeline-db.js";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import {
  ABSENT,
  cityIssueSlugs,
  loadArchive,
  loadLabelsBySlug,
  loadProposedLabels,
  runExtractors,
  score,
  type LabelSet,
} from "./phase0.js";

const program = new Command("civic-extract");

program
  .command("run")
  .description("Extract positions from archived sources. Writes DRAFTs; publishes nothing.")
  .option("--source <id>")
  .option("--candidate <slug>")
  .option("--limit <n>", "cap sources processed", (v) => Number(v))
  .option("--model-a <id>", "first extractor model", MODEL_A)
  .option("--model-b <id>", "second, independent extractor model", MODEL_B)
  .option("--dry-run", "report what would happen and write nothing")
  .action(async (o) => {
    const report = await runExtraction({
      ...(o.source ? { sourceId: o.source } : {}),
      ...(o.candidate ? { candidateSlug: o.candidate } : {}),
      ...(o.limit ? { limit: o.limit } : {}),
      modelA: o.modelA,
      modelB: o.modelB,
      dryRun: !!o.dryRun,
    });

    for (const d of report.details) {
      console.log(`\n${d.candidate ?? "(unlinked)"} — ${d.sourceUrl}`);
      if (d.error) console.log(`  ERROR ${d.error}`);
      if (d.agreed.length) console.log(`  draft:   ${d.agreed.join(", ")}`);
      if (d.flagged.length) console.log(`  review:  ${d.flagged.join(", ")}`);
      if (d.rejected.length) console.log(`  dropped: ${d.rejected.join(", ")}`);
    }

    console.log(
      `\n${report.sources} sources · ${report.drafts} drafts · ${report.flagged} to review · ` +
        `${report.rejectedQuotes} quotes dropped · ${report.refusals} refusals · ` +
        `${report.costCents.toFixed(2)}c` + (o.dryRun ? "  (dry run, nothing written)" : ""),
    );
    await prisma.$disconnect();
  });

program
  .command("fidelity")
  .description("Phase 0: score the extractor against the archived candidate pages. Writes nothing to the DB.")
  .option("--dir <path>", "archive directory", "docs/phase0")
  .option("--out <path>", "where to write the results", "docs/PHASE0_RESULTS.md")
  .action(async (o) => {
    const slugs = ["chad-west", "jeff-kitner", "bill-roth", "paula-blackmon", "adam-bazaldua"];
    const docs = loadArchive(o.dir, slugs);
    const issueSlugs = await cityIssueSlugs();

    const labelSets = new Map<string, LabelSet>();
    labelSets.set("drafted", loadProposedLabels(`${o.dir}/proposed-labels.json`, docs));
    for (const [name, file] of [
      ["commitment", `${o.dir}/independent-commitment.json`],
      ["voter", `${o.dir}/independent-voter.json`],
    ] as const) {
      if (existsSync(file)) labelSets.set(name, loadLabelsBySlug(JSON.parse(readFileSync(file, "utf8"))));
    }

    console.log(
      `${docs.length} documents · ${issueSlugs.length} issues · ` +
        `${labelSets.size} label set(s): ${[...labelSets.keys()].join(", ")}`,
    );

    const run = await runExtractors(docs, issueSlugs);
    const report = score(run.cells, labelSets);

    const quoteValidity =
      run.quotesOffered === 0 ? 100 : (100 * (run.quotesOffered - run.rejected.length)) / run.quotesOffered;
    const p = (n: number) => `${n.toFixed(1)}%`;

    console.log(`\nquote validity      ${p(quoteValidity)}  (${run.rejected.length} of ${run.quotesOffered} rejected)`);
    console.log(`stance agreement    ${p(report.exactAgreement)} exact · ${p(report.directionAgreement)} same direction`);
    console.log(`  scored on ${report.scoredRows} rows; ${report.contestedRows} contested between readers`);
    for (const [m, v] of Object.entries(report.modelAgreement)) console.log(`  ${m.padEnd(20)} ${p(v)}`);
    console.log(`absence accuracy    ${p(report.absenceAccuracy)} of ${report.absenceRows} silent rows`);
    console.log(`false absence       ${p(report.falseAbsence)} of ${report.statedRows} stated rows`);
    console.log(`model disagreement  ${report.flaggedRows} rows produced no answer`);
    console.log(`cost                ${run.costCents.toFixed(2)}c total · ${(run.costCents / docs.length).toFixed(2)}c per candidate`);

    writeFileSync(o.out, renderResults({ docs, issueSlugs, run, report, quoteValidity, labelSets }));
    console.log(`\nwrote ${o.out}`);
    await prisma.$disconnect();
  });

/** The results document. Written by the harness so the numbers cannot drift from the run. */
function renderResults(x: {
  docs: Array<{ slug: string; candidate: string; url: string; chars: number }>;
  issueSlugs: string[];
  run: Awaited<ReturnType<typeof runExtractors>>;
  report: ReturnType<typeof score>;
  quoteValidity: number;
  labelSets: Map<string, LabelSet>;
}): string {
  const p = (n: number) => `${n.toFixed(1)}%`;
  const names = [...x.labelSets.keys()];
  const L: string[] = [];

  L.push("# Phase 0 fidelity test — results");
  L.push("");
  L.push("Generated by `pnpm extract fidelity`. Do not edit by hand: rerun it.");
  L.push("");
  L.push("## What these numbers are, and are not");
  L.push("");
  L.push(
    "The labels scored against here were written by **models**, not by a person. Three readers " +
      "with three different rubrics, none of which had seen the extractor prompt. That measures " +
      "whether independently instructed readers converge on the same answer. It does **not** " +
      "establish that the answer is right, and it should not be quoted as if it did.",
  );
  L.push("");
  L.push(
    "Quote validity is the exception and is worth more than the rest: a quote either is a span " +
      "of the archived document or it is not. No judgment is involved.",
  );
  L.push("");
  L.push("## Headline");
  L.push("");
  L.push("| Measure | Value | Judgment involved |");
  L.push("|---|---|---|");
  L.push(`| Quote validity | **${p(x.quoteValidity)}** (${x.run.rejected.length}/${x.run.quotesOffered} rejected) | none |`);
  L.push(`| Stance agreement, exact | ${p(x.report.exactAgreement)} | yes |`);
  L.push(`| Stance agreement, direction only | ${p(x.report.directionAgreement)} | yes |`);
  L.push(`| Absence accuracy | ${p(x.report.absenceAccuracy)} of ${x.report.absenceRows} silent rows | little |`);
  L.push(`| False absence | ${p(x.report.falseAbsence)} of ${x.report.statedRows} stated rows | little |`);
  L.push(`| Rows with no answer (models disagreed) | ${x.report.flaggedRows} | none |`);
  L.push(`| Rows contested between readers | ${x.report.contestedRows} of ${x.report.rows.length} | — |`);
  L.push(`| Cost per candidate | ${(x.run.costCents / x.docs.length).toFixed(2)}c | none |`);
  L.push("");
  L.push("Per model, against the readers' consensus:");
  L.push("");
  L.push("| Model | Exact agreement |");
  L.push("|---|---|");
  for (const [m, v] of Object.entries(x.report.modelAgreement)) L.push(`| \`${m}\` | ${p(v)} |`);
  L.push("");

  L.push("## Documents");
  L.push("");
  L.push("| Candidate | Chars | Page |");
  L.push("|---|---|---|");
  for (const d of x.docs) L.push(`| ${d.candidate} | ${d.chars} | ${d.url} |`);
  L.push("");

  const contested = x.report.rows.filter((r) => r.consensus === null);
  L.push(`## Contested rows — ${contested.length}`);
  L.push("");
  L.push(
    "The readers did not agree with each other here, so there is nothing to score against. " +
      "These, and only these, are worth a person's time.",
  );
  L.push("");
  L.push(`| Candidate | Issue | ${names.join(" | ")} | Extractor |`);
  L.push(`|---|---|${names.map(() => "---").join("|")}|---|`);
  for (const r of contested) {
    L.push(
      `| ${r.slug} | \`${r.issueSlug}\` | ${names.map((n) => r.labels[n] ?? "—").join(" | ")} | ${r.pipeline} |`,
    );
  }
  L.push("");

  const missed = x.report.rows.filter((r) => r.consensus !== null && !r.exact);
  L.push(`## Where the extractor disagreed with an agreed label — ${missed.length}`);
  L.push("");
  L.push("| Candidate | Issue | Readers agreed | Extractor | Same direction |");
  L.push("|---|---|---|---|---|");
  for (const r of missed) {
    L.push(
      `| ${r.slug} | \`${r.issueSlug}\` | ${r.consensus} | ${r.pipeline} | ${r.sameDirection ? "yes" : "no"} |`,
    );
  }
  L.push("");

  if (x.run.rejected.length) {
    L.push("## Quotes rejected by the verbatim gate");
    L.push("");
    L.push("| Candidate | Issue | Reason |");
    L.push("|---|---|---|");
    for (const r of x.run.rejected) L.push(`| ${r.slug} | \`${r.issueSlug}\` | ${r.reason} |`);
    L.push("");
  }

  L.push("## Full grid");
  L.push("");
  L.push(`| Candidate | Issue | ${names.join(" | ")} | model A | model B | pipeline |`);
  L.push(`|---|---|${names.map(() => "---").join("|")}|---|---|---|`);
  for (const r of x.report.rows) {
    const cell = (s: string) => (s === ABSENT ? "—" : s);
    L.push(
      `| ${r.slug} | \`${r.issueSlug}\` | ${names.map((n) => cell(r.labels[n] ?? "?")).join(" | ")} | ` +
        `${cell(r.a)} | ${cell(r.b)} | ${cell(r.pipeline)} |`,
    );
  }
  L.push("");
  return L.join("\n");
}

program.parseAsync();
